In [42]:
# DataFrames: Combining Multiple Series together it Becomes a DataFrame

# Creating a DataFrame

import numpy as np
import pandas as pd

In [43]:
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age': [28,34,29,42],
    'City': ['New York','Paris','Berlin','London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [55]:
data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter', 29,'Berlin',62000],
    ['Linda', 42, 'London', 85000]
]
labels = ['Name', 'age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = labels)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [56]:
# Selection and Indexing of columns

df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [57]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [58]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [59]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [60]:
# Creating a New Columns

df2['Designation'] = ['Software Engineer','Data Analyst', 'Doctor', 'Product Engineer']
df2

    Name  age      City  Salary        Designation
0   John   28  New York   65000  Software Engineer
1   Anna   34     Paris   70000       Data Analyst
2  Peter   29    Berlin   62000             Doctor
3  Linda   42    London   85000   Product Engineer

In [61]:
# Removing a Column

df2.drop('Designation', axis = 1,inplace = True)

In [62]:
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [63]:
# Removing a Row 

df2.drop(0)

    Name  age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [64]:
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [65]:
# Selecting a Row

df2.loc[0]

Name          John
age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [66]:
#Selecting Subsets of Rows and Columns

df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [67]:
df2.loc[[2,3]][['Name','age']]

    Name  age
2  Peter   29
3  Linda   42

In [68]:
# Conditional Selection

df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [82]:
df2[df2['age'] > 30]

    Name  age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [90]:
df2[(df2['age'] > 30) & (df2['City'] == 'Paris')]

   Name  age   City  Salary
1  Anna   34  Paris   70000